#!/bin/sh
# /etc/hotplug.d/usb/20-modem-detect

case "$ACTION" in
    add)
        case "$PRODUCT" in
            # Dell modems
            413c/81d7/*|413c/81d9/*)
                logger "Dell modem detected: $PRODUCT"
                if [ -f /etc/init.d/modemmanager ]; then
                    (sleep 5; /etc/init.d/modemmanager restart) &
                else
                    logger "ERROR: modemmanager init script not found"
                fi
                ;;
            # Tw 5G modems  
            1e2d/00b3/*|1e2d/00b7/*)
                logger "Tw 5G modem detected: $PRODUCT"
                if [ -f /etc/init.d/modemmanager ]; then
                    (sleep 5; /etc/init.d/modemmanager restart) &
                else
                    logger "ERROR: modemmanager init script not found"
                fi
                ;;
            # Other modems
            12d1/15c1/*|2cb7/0007/*|0489/e0b4/*)
                logger "other modems: $PRODUCT"
                if [ -f /etc/init.d/modemmanager ]; then
                    (sleep 5; /etc/init.d/modemmanager restart) &
                else
                    logger "ERROR: modemmanager init script not found"
                fi
                ;;
        esac
        ;;
    remove)
        case "$PRODUCT" in
            413c/81d7/*|12d1/15c1/*|2cb7/0007/*|0489/e0b4/*|1e2d/00b3/*|1e2d/00b7/*)
                logger "Modem removed: $PRODUCT"
                ;;
        esac
        ;;
esac