#!/bin/sh
# /etc/hotplug.d/usb/20-modem-detect

is_supported_modem() {
    case "$PRODUCT" in
        # Dell modems
        413c/81d7/*|413c/81d9/*)
            return 0 ;;
        # Tw 5G modems  
        1e2d/00b3/*|1e2d/00b7/*)
            return 0 ;;
        # Other modems
        12d1/15c1/*|2cb7/0007/*|0489/e0b4/*)
            return 0 ;;
        *)
            return 1 ;;
    esac
}

restart_modemmanager() {
    if [ -f /etc/init.d/modemmanager ]; then
        logger "Restarting modemmanager for modem: $PRODUCT"
        (sleep 5; /etc/init.d/modemmanager restart) &
    else
        logger "ERROR: modemmanager init script not found"
    fi
}

case "$ACTION" in
    add)
        if is_supported_modem; then
            logger "Modem detected: $PRODUCT"
            restart_modemmanager
        fi
        ;;
    remove)
        if is_supported_modem; then
            logger "Modem removed: $PRODUCT"
        fi
        ;;
esac